// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI65i7Xqew6H_eqghN2F6dBW792iUaya4',
    appId: '1:742667079284:web:1ca76ddef88ca727814b21',
    messagingSenderId: '742667079284',
    projectId: 'smartfin-7a8db',
    authDomain: 'smartfin-7a8db.firebaseapp.com',
    storageBucket: 'smartfin-7a8db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdAsMQy03i1kZL8P_UwcZJEaMvZlN-xYw',
    appId: '1:742667079284:android:bf8035a622880548814b21',
    messagingSenderId: '742667079284',
    projectId: 'smartfin-7a8db',
    storageBucket: 'smartfin-7a8db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEuhL3evY6rgeBj0Gb8LhYBtF2sCm3K50',
    appId: '1:742667079284:ios:cf54535ec55ef744814b21',
    messagingSenderId: '742667079284',
    projectId: 'smartfin-7a8db',
    storageBucket: 'smartfin-7a8db.appspot.com',
    iosBundleId: 'com.example.smartfin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEuhL3evY6rgeBj0Gb8LhYBtF2sCm3K50',
    appId: '1:742667079284:ios:cf54535ec55ef744814b21',
    messagingSenderId: '742667079284',
    projectId: 'smartfin-7a8db',
    storageBucket: 'smartfin-7a8db.appspot.com',
    iosBundleId: 'com.example.smartfin',
  );
}
